# Generated by Django 4.1 on 2025-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
